import ToastProvider from "@/components/ToastProvider";
import "./globals.css";
import { Bricolage_Grotesque } from 'next/font/google'
import GlobalProvider from "@/components/Aplication/GlobalProvider";

const font = Bricolage_Grotesque({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ["latin"],
  display: "swap"
})

export const metadata = {
  title: "E-Commerce WebPage",
  description: "Generated by Vicky Bisht",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <GlobalProvider>
          {children}
          <ToastProvider />
        </GlobalProvider>
      </body>
    </html>
  );
}
